In [8]:
import pandas as pd

In [29]:
conso_sheets_list = ['Primary Energy Consumption',
                     'Oil Consumption - EJ',
                     'Gas Consumption - EJ',
                     'Coal Consumption - EJ',
                     'Nuclear Consumption - EJ',
                     'Hydro Consumption - EJ',
                     'Solar Consumption - EJ',
                     'Wind Consumption - EJ',
                     'Geo Biomass Other - EJ',
                     'Biofuels Consumption - PJ']

def excel_to_dataframe(sheet:str):
  df = pd.read_excel('data_brut/bp-stats-review-2020-all-data.xlsx',
                    sheet_name=sheet,
                    skiprows=[0,1], skipfooter=8)
  df = df.drop(['2019.1','2008-18','2019.2'],axis=1)
  df = df.transpose()
  new_header = df.iloc[0]
  df = df[1:]
  df.columns = new_header
  df = df.dropna(1,how='all')
  df = df.dropna(0, how='all')
  return df

data_list = []
for sheet in conso_sheets_list:
  clean_df = excel_to_dataframe(sheet)
  data_list.append(clean_df)

In [17]:
data_list[9]

Petajoules,Canada,Mexico,US,Total North America,Argentina,Brazil,Colombia,Other S. & Cent. America,Total S. & Cent. America,Austria,...,US,Canada & Mexico,Brazil,Other S. & Cent. America,Europe,CIS,Middle East,Africa,Asia Pacific,Total World
1990,0,0,63.6094,63.6094,0,245.14,0,60.9196,306.06,0.265603,...,0,0,0,0,0.265603,0,0,0,0,0.265603
1991,0,0,73.7061,73.7061,0,255.562,0,61.5062,317.069,0.294804,...,0,0,0,0,0.294804,0,0,0,0,0.294804
1992,0,0,83.8028,83.8028,0,250.069,0,49.0592,299.128,0.326514,...,0,0,0,0,0.618758,0,0,0,0,0.618758
1993,0,0,97.9244,97.9244,0,260.775,0,39.4097,300.184,0.375333,...,0,0,0,0,0.995474,0,0,0,0,0.995474
1994,0,0,109.659,109.659,0,278.147,0,39.0162,317.163,0.264643,...,0,0,0,0,4.48639,0,0,0,0,4.48639
1995,0,0,117.627,117.627,0,287.615,0,41.203,328.818,0.47242,...,0,0,0,0,7.66932,0,0,0,0,7.66932
1996,0,0,84.3712,84.3712,0,299.425,0,39.0534,338.479,0.46332,...,0,0,0,0,11.1597,0,0,0,0,11.1597
1997,0,0,106.836,106.836,0,289.304,0,40.821,330.125,0.548697,...,0,0,0,0,15.1798,0,0,0,0,15.1798
1998,0,0,118.052,118.052,0,283.977,0,41.0443,325.022,0.561315,...,0,0,0,0,13.6025,0,0,0,0,13.6025
1999,0,0,122.741,122.741,0,284.631,0,39.6898,324.321,0.660715,...,0,0,0,0,15.8076,0,0,0,0,15.8076
2000,0,0,140.667,140.667,0,243.679,0,39.6415,283.321,0.712607,...,0,0,0,0,26.1407,0,0,0,0,26.1407
2001,0,0,149.372,149.372,0,230.705,0,37.9117,268.617,0.817464,...,1.27945,0,0,0,30.9057,0,0,0,0.190496,32.3756
2002,0,3.30382,178.413,181.717,0,260.552,0,36.6473,297.199,0.845744,...,2.0386,0,0,0,38.3623,0,0,0,0.190496,40.5914
2003,0,3.25887,242.112,245.371,0,247.652,0,37.2256,284.877,0.877681,...,1.68336,0,0,0,47.9673,0,0,0,0.190496,49.8411
2004,0,3.32629,305.554,308.88,0,276.127,0,36.053,312.18,0.894747,...,3.34445,0,0,0,65.9305,0,0,0,0.44275,69.7177
2005,0,3.68589,356.613,360.299,0,298.815,0.0281792,34.5369,333.38,3.404,...,11.3175,0,0.032917,0,103.75,0,0,0,5.1162,120.217
2006,18.3287,3.75332,498.837,520.919,0,278.601,0.277464,27.0432,305.921,12.2285,...,32.5126,0.925201,2.27127,2.92958,162.996,0,0,0,11.6301,213.265
2007,22.3978,3.61847,629.887,655.903,0,386.225,0.331486,16.5461,403.103,14.2691,...,44.0736,0.925035,13.2985,2.92958,229.571,0,0,0,22.4565,313.254
2008,30.3472,3.73084,861.654,895.733,0,515.366,0.474858,17.557,533.398,17.4357,...,37.8243,1.11744,37.0316,4.18918,303.747,0.296,0,0,43.9466,428.152
2009,34.3315,4.04549,979.061,1017.44,0,564.461,0.664551,20.2637,585.389,22.1133,...,40.1017,1.96368,51.5151,6.03735,356.924,0.851,0,0,58.1011,515.494
2010,35.3003,4.22529,1126.37,1165.89,21.4646,601.669,1.05514,24.4126,648.602,21.5671,...,32.4064,4.14758,78.902,26.4695,418.369,1.406,0,0,66.7677,628.468
2011,55.1487,3.91064,1207.34,1266.4,31.6796,548.789,1.30851,26.6775,608.455,21.6696,...,110.421,9.05204,84.6361,36.5889,446.152,1.147,0,0,81.2506,769.248
2012,64.6259,4.51747,1207.98,1277.12,39.1559,518.991,1.33953,31.4968,590.983,21.4459,...,112.025,11.521,90.641,45.0417,493.188,1.221,0,0,110.531,864.169
2013,72.6734,4.51747,1302.38,1379.58,43.4142,610.089,1.38643,33.9842,688.874,18.8661,...,178.04,12.1793,96.4015,45.2559,446.784,0.962,0,0,139.706,919.328
2014,76.7119,6.98971,1320.32,1404.02,50.7984,673.235,1.42007,34.9471,760.401,23.4122,...,176.546,12.3439,111.631,48.7464,484.62,1.02582,0,0.592,207.03,1042.54
2015,74.8353,7.41674,1372.72,1454.97,55.4197,798.076,1.51409,37.0462,892.056,27.8643,...,186.179,9.8754,129.918,51.6199,484.077,0.918338,0,1.147,136.358,1000.09
2016,75.8088,7.86623,1481.25,1564.92,58.819,725.014,1.42243,38.8876,824.143,23.1129,...,259.854,10.5337,125.068,52.1735,496.437,0.88181,0,1.591,198.257,1144.8
2017,78.5041,8.31573,1479.72,1566.54,67.6234,760.991,1.38749,39.1145,869.116,20.1755,...,247.375,12.5085,141.604,56.3961,542.277,0.924221,0,2.146,179.642,1182.87
2018,82.2577,8.31573,1463.08,1553.66,64.6064,882.106,1.40379,40.6369,988.753,21.0745,...,236.243,12.8476,175.628,53.7168,598.503,0.971493,0,2.775,257.572,1338.26
2019,83.9575,8.42811,1462.29,1554.67,65.9592,975.327,1.44335,42.5442,1085.27,21.3789,...,225.621,12.1135,194.996,55.2854,582.992,0.976322,0,3.33,386.558,1461.87

In [7]:
energy_types = ['Primary', 'Oil', 'Gas', 'Coal', 'Nuclear', 'Hydro', 'Solar', 'Wind', 'Geo Biomass', 'Biofuel']
types_df = pd.DataFrame(energy_types)
types_df.rename(columns={0 : 'name'}, inplace=True)
types_df
types_df.to_csv("Sauvegardes_clean_csv/energy_types.csv")

In [30]:
#conversion en PJ

def PJ_to_EJ(x):
    return x * 0.001

data_list[9] = PJ_to_EJ(data_list[9])
data_list[9]

Petajoules,Canada,Mexico,US,Total North America,Argentina,Brazil,Colombia,Other S. & Cent. America,Total S. & Cent. America,Austria,...,US,Canada & Mexico,Brazil,Other S. & Cent. America,Europe,CIS,Middle East,Africa,Asia Pacific,Total World
1990,0,0,0.0636094,0.0636094,0,0.24514,0,0.0609196,0.30606,0.000265603,...,0,0,0,0,0.000265603,0,0,0,0,0.000265603
1991,0,0,0.0737061,0.0737061,0,0.255562,0,0.0615062,0.317069,0.000294804,...,0,0,0,0,0.000294804,0,0,0,0,0.000294804
1992,0,0,0.0838028,0.0838028,0,0.250069,0,0.0490592,0.299128,0.000326514,...,0,0,0,0,0.000618758,0,0,0,0,0.000618758
1993,0,0,0.0979244,0.0979244,0,0.260775,0,0.0394097,0.300184,0.000375333,...,0,0,0,0,0.000995474,0,0,0,0,0.000995474
1994,0,0,0.109659,0.109659,0,0.278147,0,0.0390162,0.317163,0.000264643,...,0,0,0,0,0.00448639,0,0,0,0,0.00448639
1995,0,0,0.117627,0.117627,0,0.287615,0,0.041203,0.328818,0.00047242,...,0,0,0,0,0.00766932,0,0,0,0,0.00766932
1996,0,0,0.0843712,0.0843712,0,0.299425,0,0.0390534,0.338479,0.00046332,...,0,0,0,0,0.0111597,0,0,0,0,0.0111597
1997,0,0,0.106836,0.106836,0,0.289304,0,0.040821,0.330125,0.000548697,...,0,0,0,0,0.0151798,0,0,0,0,0.0151798
1998,0,0,0.118052,0.118052,0,0.283977,0,0.0410443,0.325022,0.000561315,...,0,0,0,0,0.0136025,0,0,0,0,0.0136025
1999,0,0,0.122741,0.122741,0,0.284631,0,0.0396898,0.324321,0.000660715,...,0,0,0,0,0.0158076,0,0,0,0,0.0158076
2000,0,0,0.140667,0.140667,0,0.243679,0,0.0396415,0.283321,0.000712607,...,0,0,0,0,0.0261407,0,0,0,0,0.0261407
2001,0,0,0.149372,0.149372,0,0.230705,0,0.0379117,0.268617,0.000817464,...,0.00127945,0,0,0,0.0309057,0,0,0,0.000190496,0.0323756
2002,0,0.00330382,0.178413,0.181717,0,0.260552,0,0.0366473,0.297199,0.000845744,...,0.0020386,0,0,0,0.0383623,0,0,0,0.000190496,0.0405914
2003,0,0.00325887,0.242112,0.245371,0,0.247652,0,0.0372256,0.284877,0.000877681,...,0.00168336,0,0,0,0.0479673,0,0,0,0.000190496,0.0498411
2004,0,0.00332629,0.305554,0.30888,0,0.276127,0,0.036053,0.31218,0.000894747,...,0.00334445,0,0,0,0.0659305,0,0,0,0.00044275,0.0697177
2005,0,0.00368589,0.356613,0.360299,0,0.298815,2.81792e-05,0.0345369,0.33338,0.003404,...,0.0113175,0,3.2917e-05,0,0.10375,0,0,0,0.0051162,0.120217
2006,0.0183287,0.00375332,0.498837,0.520919,0,0.278601,0.000277464,0.0270432,0.305921,0.0122285,...,0.0325126,0.000925201,0.00227127,0.00292958,0.162996,0,0,0,0.0116301,0.213265
2007,0.0223978,0.00361847,0.629887,0.655903,0,0.386225,0.000331486,0.0165461,0.403103,0.0142691,...,0.0440736,0.000925035,0.0132985,0.00292958,0.229571,0,0,0,0.0224565,0.313254
2008,0.0303472,0.00373084,0.861654,0.895733,0,0.515366,0.000474858,0.017557,0.533398,0.0174357,...,0.0378243,0.00111744,0.0370316,0.00418918,0.303747,0.000296,0,0,0.0439466,0.428152
2009,0.0343315,0.00404549,0.979061,1.01744,0,0.564461,0.000664551,0.0202637,0.585389,0.0221133,...,0.0401017,0.00196368,0.0515151,0.00603735,0.356924,0.000851,0,0,0.0581011,0.515494
2010,0.0353003,0.00422529,1.12637,1.16589,0.0214646,0.601669,0.00105514,0.0244126,0.648602,0.0215671,...,0.0324064,0.00414758,0.078902,0.0264695,0.418369,0.001406,0,0,0.0667677,0.628468
2011,0.0551487,0.00391064,1.20734,1.2664,0.0316796,0.548789,0.00130851,0.0266775,0.608455,0.0216696,...,0.110421,0.00905204,0.0846361,0.0365889,0.446152,0.001147,0,0,0.0812506,0.769248
2012,0.0646259,0.00451747,1.20798,1.27712,0.0391559,0.518991,0.00133953,0.0314968,0.590983,0.0214459,...,0.112025,0.011521,0.090641,0.0450417,0.493188,0.001221,0,0,0.110531,0.864169
2013,0.0726734,0.00451747,1.30238,1.37958,0.0434142,0.610089,0.00138643,0.0339842,0.688874,0.0188661,...,0.17804,0.0121793,0.0964015,0.0452559,0.446784,0.000962,0,0,0.139706,0.919328
2014,0.0767119,0.00698971,1.32032,1.40402,0.0507984,0.673235,0.00142007,0.0349471,0.760401,0.0234122,...,0.176546,0.0123439,0.111631,0.0487464,0.48462,0.00102582,0,0.000592,0.20703,1.04254
2015,0.0748353,0.00741674,1.37272,1.45497,0.0554197,0.798076,0.00151409,0.0370462,0.892056,0.0278643,...,0.186179,0.0098754,0.129918,0.0516199,0.484077,0.000918338,0,0.001147,0.136358,1.00009
2016,0.0758088,0.00786623,1.48125,1.56492,0.058819,0.725014,0.00142243,0.0388876,0.824143,0.0231129,...,0.259854,0.0105337,0.125068,0.0521735,0.496437,0.00088181,0,0.001591,0.198257,1.1448
2017,0.0785041,0.00831573,1.47972,1.56654,0.0676234,0.760991,0.00138749,0.0391145,0.869116,0.0201755,...,0.247375,0.0125085,0.141604,0.0563961,0.542277,0.000924221,0,0.002146,0.179642,1.18287
2018,0.0822577,0.00831573,1.46308,1.55366,0.0646064,0.882106,0.00140379,0.0406369,0.988753,0.0210745,...,0.236243,0.0128476,0.175628,0.0537168,0.598503,0.000971493,0,0.002775,0.257572,1.33826
2019,0.0839575,0.00842811,1.46229,1.55467,0.0659592,0.975327,0.00144335,0.0425442,1.08527,0.0213789,...,0.225621,0.0121135,0.194996,0.0552854,0.582992,0.000976322,0,0.00333,0.386558,1.46187

In [31]:
energy_types = ['Primary', 'Oil', 'Gas', 'Coal', 'Nuclear', 'Hydro', 'Solar', 'Wind', 'Geo Biomass', 'Biofuel']

locations_to_drop=[  'Total North America',
'Total S. & Cent. America',
 'Total Europe',
  'Total Middle East',
'Total Africa',
'Total Asia Pacific',
 'Total World',
 'of which: OECD',
 '                 Non-OECD',
 '                 European Union #'
                  'European Union'
                  'Europe',' of which: OECD',
       '                Non-OECD', '                European Union',
       'Canada & Mexico', 'Other S. & Cent. America', 'Europe',
       'CIS', 'Middle East', 'Africa', 'Asia Pacific',
       '                Non-OECD', '                European Union',
       'Canada & Mexico', 'Other S. & Cent. America', 'Europe',
       'CIS', 'Middle East', 'Africa', 'Asia Pacific','Total Europe ','Total CIS','                 European Union #']

n=0

for df in data_list:
    df.rename_axis(energy_types[n] + " EJ", axis="columns", inplace = True)
    n+=1
    
    for location in  locations_to_drop:
        try:
            df.drop([location], axis=1, inplace = True )
        except KeyError:
            pass
    
data_list[9]                   
#dropping 2 last columns Brazil and US in Biofuel df


data_list[9] = data_list[9].iloc[:,:-4]

In [32]:
# Sauvegarde en CSV
types = ['Primary', 'Oil', 'Gas', 'Coal', 'Nuclear', 'Hydro', 'Solar', 'Wind', 'Geo Biomass', 'Biofuel']
n=0

for df in data_list:
    
    df.to_csv("Sauvegardes_clean_csv/cons_csv/"+ types[n]+".csv")
    n += 1

In [9]:
list_country = ['Canada',
 'Mexico',
 'US',
 'Argentina',
 'Brazil',
 'Colombia',
 'Ecuador',
 'Peru',
 'Trinidad & Tobago',
 'Venezuela',
 'Denmark',
 'Italy',
 'Norway',
 'Romania',
 'United Kingdom',
 'Other Europe',
 'Azerbaijan',
 'Kazakhstan',
 'Russian Federation',
 'Turkmenistan',
 'USSR',
 'Uzbekistan',
 'Other CIS',
 'Iran',
 'Iraq',
 'Kuwait',
 'Oman',
 'Qatar',
 'Saudi Arabia',
 'Syria',
 'United Arab Emirates',
 'Yemen',
 'Other Middle East',
 'Algeria',
 'Angola',
 'Chad',
 'Republic of Congo ',
 'Egypt',
 'Equatorial Guinea',
 'Gabon',
 'Libya',
 'Nigeria',
 'South Sudan',
 'Sudan',
 'Tunisia',
 'Other Africa',
 'Australia',
 'Brunei',
 'China',
 'India',
 'Indonesia',
 'Malaysia',
 'Thailand',
 'Vietnam',
 'Other Asia Pacific',
 'Bolivia',
 'Germany',
 'Netherlands',
 'Poland',
 'Ukraine',
 'Bahrain',
 'Bangladesh',
 'Myanmar',
 'Pakistan',
 'Bulgaria',
 'Czech Republic',
 'Greece',
 'Hungary',
 'Serbia',
 'Spain',
 'Turkey',
 'South Africa',
 'Zimbabwe',
 'Japan',
 'Mongolia',
 'New Zealand',
 'South Korea',
 'Chile',
 'Central America',
 'Other Caribbean',
 'Other South America',
 'Austria',
 'Belgium',
 'Croatia',
 'Cyprus',
 'Estonia',
 'Finland',
 'France',
 'Iceland',
 'Ireland',
 'Latvia',
 'Lithuania',
 'Luxembourg',
 'North Macedonia',
 'Portugal',
 'Slovakia',
 'Slovenia',
 'Sweden',
 'Switzerland',
 'Belarus',
 'Israel',
 'Morocco',
 'Eastern Africa',
 'Middle Africa',
 'Western Africa',
 'Other Northern Africa',
 'Other Southern Africa',
 'China Hong Kong SAR',
 'Philippines',
 'Singapore',
 'Sri Lanka',
 'Taiwan']

112

In [235]:

locations_df = pd.DataFrame(list_country)

dic = {'Canada':1,
 'Mexico':1,
 'US':1,
 'Argentina':2,
 'Brazil':2,
 'Colombia':2,
 'Ecuador':2,
 'Peru':2,
 'Trinidad & Tobago':2,
 'Venezuela':2,
 'Denmark':3,
 'Italy':3,
 'Norway':3,
 'Romania':3,
 'United Kingdom':3,
 'Other Europe':3,
 'Azerbaijan':4,
 'Kazakhstan':4,
 'Russian Federation':4,
 'Turkmenistan':4,
 'USSR':4,
 'Uzbekistan':4,
 'Other CIS':4,
 'Iran':5,
 'Iraq':5,
 'Kuwait':5,
 'Oman':5,
 'Qatar':5,
 'Saudi Arabia':5,
 'Syria':5,
 'United Arab Emirates':5,
 'Yemen':5,
 'Other Middle East':5,
 'Algeria':6,
 'Angola':6,
 'Chad':6,
 'Republic of Congo ':6,
 'Egypt':6,
 'Equatorial Guinea':6,
 'Gabon':6,
 'Libya':6,
 'Nigeria':6,
 'South Sudan':6,
 'Sudan':6,
 'Tunisia':6,
 'Other Africa':6,
 'Australia':7,
 'Brunei':7,
 'China':7,
 'India':7,
 'Indonesia':7,
 'Malaysia':7,
 'Thailand':7,
 'Vietnam':7,
 'Other Asia Pacific':7,
 'Bolivia':2,
 'Germany':3,
 'Netherlands':3,
 'Poland':3,
 'Ukraine':3,
 'Bahrain':5,
 'Bangladesh':7,
 'Myanmar':7,
 'Pakistan':7,
 'Bulgaria':3,
 'Czech Republic':3,
 'Greece':3,
 'Hungary':3,
 'Serbia':3,
 'Spain':3,
 'Turkey':3,
 'South Africa':6,
 'Zimbabwe':6,
 'Japan':7,
 'Mongolia':7,
 'New Zealand':7,
 'South Korea':7,
 'Chile':2,
 'Central America':2,
 'Other Caribbean':2,
 'Other South America':2,
 'Austria':3,
 'Belgium':3,
 'Croatia':3,
 'Cyprus':3,
 'Estonia':3,
 'Finland':3,
 'France':3,
 'Iceland':3,
 'Ireland':3,
 'Latvia':3,
 'Lithuania':3,
 'Luxembourg':3,
 'North Macedonia':3,
 'Portugal':3,
 'Slovakia':3,
 'Slovenia':3,
 'Sweden':3,
 'Switzerland':3,
 'Belarus':3,
 'Israel':5,
 'Morocco':6,
 'Eastern Africa':6,
 'Middle Africa':6,
 'Western Africa':6,
 'Other Northern Africa':6,
 'Other Southern Africa':6,
 'China Hong Kong SAR':7,
 'Philippines':7,
 'Singapore':7,
 'Sri Lanka':7,
 'Taiwan':7}



locations_df['region_id']=locations_df

In [236]:
locations_df.rename(columns={0:'name'},inplace=True)

In [237]:
locations_df['region_id']= locations_df['region_id'].map(dic)
locations_df

                    name  region_id
0                 Canada          1
1                 Mexico          1
2                     US          1
3              Argentina          2
4                 Brazil          2
..                   ...        ...
107  China Hong Kong SAR          7
108          Philippines          7
109            Singapore          7
110            Sri Lanka          7
111               Taiwan          7

[112 rows x 2 columns]

In [238]:
locations_df.to_csv("Sauvegardes_clean_csv/locations.csv")

In [244]:
regions= ['North America',
'S. & Cent. America',
'Europe',
'CIS',
'Middle East',
'Africa',
'Asia Pacific',
]

regions_df = pd.DataFrame(regions)

regions_df.rename(columns={0:'name'}, inplace = True)

regions_df.to_csv("Sauvegardes_clean_csv/regions.csv")

   Unnamed: 0                name
0           0       North America
1           1  S. & Cent. America
2           2              Europe
3           3                 CIS
4           4         Middle East
5           5              Africa
6           6        Asia Pacific